"""add jira-connection table

Revision ID: 5fa4d5ae63c5
Revises: f54af4d769ed
Create Date: 2025-10-17 19:24:18.473373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa4d5ae63c5'
down_revision: Union[str, Sequence[str], None] = 'f54af4d769ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'functional_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('functional_role', postgresql.ENUM('FRONTEND_DEV', 'BACKEND_DEV', 'NETWORK_ENGINEER', 'DATABASE_ADMIN', 'HARDWARE_SUPPORT', 'SECURITY_ANALYST', 'GENERAL_SUPPORT', name='functionalrole'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
