"""add jira-projects table

Revision ID: 7c34d1669a6d
Revises: a642d769bfc8
Create Date: 2025-10-18 00:38:25.689157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c34d1669a6d'
down_revision: Union[str, Sequence[str], None] = 'a642d769bfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jira_integration_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('lead_account_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['jira_integration_id'], ['jira_connection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jira_project')
    # ### end Alembic commands ###
