"""add jira-connection table

Revision ID: a642d769bfc8
Revises: 5fa4d5ae63c5
Create Date: 2025-10-17 19:27:11.296688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a642d769bfc8'
down_revision: Union[str, Sequence[str], None] = '5fa4d5ae63c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_connection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jira_domain', sa.String(), nullable=True),
    sa.Column('jira_email', sa.String(), nullable=False),
    sa.Column('jira_api_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_connection_jira_domain'), 'jira_connection', ['jira_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_connection_jira_domain'), table_name='jira_connection')
    op.drop_table('jira_connection')
    # ### end Alembic commands ###
