"""add jira-projects table

Revision ID: de070fdf1568
Revises: 7c34d1669a6d
Create Date: 2025-10-18 01:12:16.587620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de070fdf1568'
down_revision: Union[str, Sequence[str], None] = '7c34d1669a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_project', sa.Column('jira_connection_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('jira_project_jira_integration_id_fkey'), 'jira_project', type_='foreignkey')
    op.create_foreign_key(None, 'jira_project', 'jira_connection', ['jira_connection_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jira_project', 'jira_integration_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_project', sa.Column('jira_integration_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jira_project', type_='foreignkey')
    op.create_foreign_key(op.f('jira_project_jira_integration_id_fkey'), 'jira_project', 'jira_connection', ['jira_integration_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jira_project', 'jira_connection_id')
    # ### end Alembic commands ###
